# Generated by Django 5.2.16 on 2026-07-28 22:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('network_map', '0003_sync_company_fields_state'),
    ]

    operations = [
        migrations.CreateModel(
            name='DIO',
            fields=[
                ('networkelement_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='network_map.networkelement')),
                ('manufacturer', models.CharField(blank=True, max_length=120, verbose_name='Fabricante')),
                ('model', models.CharField(blank=True, max_length=120, verbose_name='Modelo')),
                ('serial_number', models.CharField(blank=True, max_length=120, verbose_name='Número de série')),
                ('connector_type', models.CharField(choices=[('sc_apc', 'SC/APC'), ('sc_upc', 'SC/UPC'), ('lc_apc', 'LC/APC'), ('lc_upc', 'LC/UPC'), ('e2000_apc', 'E2000/APC'), ('other', 'Outro')], default='sc_apc', max_length=20, verbose_name='Tipo de conector')),
                ('tray_capacity', models.PositiveSmallIntegerField(default=1, verbose_name='Quantidade de bandejas')),
                ('port_capacity', models.PositiveSmallIntegerField(default=24, verbose_name='Quantidade de portas')),
                ('notes', models.TextField(blank=True, verbose_name='Observações')),
                ('pop', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='dios', to='network_map.pop', verbose_name='POP')),
                ('rack', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='dios', to='network_map.rack', verbose_name='Rack')),
                ('rack_equipment', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='dio', to='network_map.rackequipment', verbose_name='Equipamento no rack')),
            ],
            options={
                'verbose_name': 'DIO',
                'verbose_name_plural': 'DIOs',
                'ordering': ['pop', 'rack', 'name'],
            },
            bases=('network_map.networkelement',),
        ),
        migrations.CreateModel(
            name='DIOTray',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('number', models.PositiveSmallIntegerField(verbose_name='Número')),
                ('name', models.CharField(blank=True, max_length=120, verbose_name='Identificação')),
                ('splice_capacity', models.PositiveSmallIntegerField(default=24, verbose_name='Capacidade de fusões')),
                ('notes', models.TextField(blank=True, verbose_name='Observações')),
                ('dio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='trays', to='optical.dio', verbose_name='DIO')),
            ],
            options={
                'verbose_name': 'Bandeja de DIO',
                'verbose_name_plural': 'Bandejas de DIO',
                'ordering': ['dio', 'number'],
            },
        ),
        migrations.CreateModel(
            name='DIOPort',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('number', models.PositiveSmallIntegerField(verbose_name='Número')),
                ('label', models.CharField(blank=True, max_length=120, verbose_name='Identificação')),
                ('connector_type', models.CharField(choices=[('sc_apc', 'SC/APC'), ('sc_upc', 'SC/UPC'), ('lc_apc', 'LC/APC'), ('lc_upc', 'LC/UPC'), ('e2000_apc', 'E2000/APC'), ('other', 'Outro')], default='sc_apc', max_length=20, verbose_name='Tipo de conector')),
                ('status', models.CharField(choices=[('normal', 'Normal'), ('warning', 'Atenção'), ('degraded', 'Degradado'), ('offline', 'Offline'), ('recovering', 'Recuperando'), ('no_data', 'Sem dados')], default='no_data', max_length=20, verbose_name='Estado operacional')),
                ('enabled', models.BooleanField(default=True, verbose_name='Ativa')),
                ('notes', models.TextField(blank=True, verbose_name='Observações')),
                ('dio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ports', to='optical.dio', verbose_name='DIO')),
                ('tray', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ports', to='optical.diotray', verbose_name='Bandeja')),
            ],
            options={
                'verbose_name': 'Porta de DIO',
                'verbose_name_plural': 'Portas de DIO',
                'ordering': ['dio', 'number'],
            },
        ),
        migrations.AddConstraint(
            model_name='diotray',
            constraint=models.UniqueConstraint(fields=('dio', 'number'), name='unique_tray_number_per_dio'),
        ),
        migrations.AddIndex(
            model_name='dioport',
            index=models.Index(fields=['dio', 'status'], name='optical_dio_dio_id_90ab6a_idx'),
        ),
        migrations.AddIndex(
            model_name='dioport',
            index=models.Index(fields=['dio', 'enabled'], name='optical_dio_dio_id_07a09a_idx'),
        ),
        migrations.AddConstraint(
            model_name='dioport',
            constraint=models.UniqueConstraint(fields=('dio', 'number'), name='unique_port_number_per_dio'),
        ),
    ]
