# Generated by Django 5.2.16 on 2026-07-28 17:15

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('network_map', '0001_initial'),
        ('olt_integration', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AlertRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=180)),
                ('scope', models.CharField(choices=[('onu', 'ONU'), ('cto', 'CTO'), ('route', 'Rota'), ('pon', 'Porta PON'), ('olt', 'OLT'), ('system', 'Sistema')], max_length=20)),
                ('enabled', models.BooleanField(default=True)),
                ('severity', models.CharField(choices=[('info', 'Informação'), ('warning', 'Aviso'), ('average', 'Média'), ('high', 'Alta'), ('disaster', 'Desastre')], default='high', max_length=20)),
                ('persistence_seconds', models.PositiveIntegerField(default=180)),
                ('recovery_seconds', models.PositiveIntegerField(default=300)),
                ('configuration', models.JSONField(blank=True, default=dict)),
            ],
            options={
                'ordering': ['scope', 'name'],
            },
        ),
        migrations.CreateModel(
            name='AlertEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('fingerprint', models.CharField(max_length=255, unique=True)),
                ('title', models.CharField(max_length=255)),
                ('message', models.TextField()),
                ('scope', models.CharField(choices=[('onu', 'ONU'), ('cto', 'CTO'), ('route', 'Rota'), ('pon', 'Porta PON'), ('olt', 'OLT'), ('system', 'Sistema')], max_length=20)),
                ('severity', models.CharField(choices=[('info', 'Informação'), ('warning', 'Aviso'), ('average', 'Média'), ('high', 'Alta'), ('disaster', 'Desastre')], max_length=20)),
                ('state', models.CharField(choices=[('open', 'Aberto'), ('acknowledged', 'Reconhecido'), ('recovering', 'Recuperando'), ('closed', 'Fechado'), ('suppressed', 'Suprimido')], default='open', max_length=20)),
                ('source_status', models.CharField(choices=[('normal', 'Normal'), ('warning', 'Atenção'), ('degraded', 'Degradado'), ('offline', 'Offline'), ('recovering', 'Recuperando'), ('no_data', 'Sem dados')], default='offline', max_length=20)),
                ('opened_at', models.DateTimeField()),
                ('acknowledged_at', models.DateTimeField(blank=True, null=True)),
                ('recovery_started_at', models.DateTimeField(blank=True, null=True)),
                ('closed_at', models.DateTimeField(blank=True, null=True)),
                ('affected_onus', models.PositiveIntegerField(default=0)),
                ('affected_ctos', models.PositiveIntegerField(default=0)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('zabbix_sent', models.BooleanField(default=False)),
                ('telegram_sent', models.BooleanField(default=False)),
                ('acknowledged_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='acknowledged_alerts', to=settings.AUTH_USER_MODEL)),
                ('cto', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='network_map.cto')),
                ('olt', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='olt_integration.olt')),
                ('onu', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='olt_integration.onu')),
                ('pon_port', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='olt_integration.ponport')),
                ('route', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='network_map.networkroute')),
                ('rule', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='alerts.alertrule')),
            ],
            options={
                'ordering': ['-opened_at'],
            },
        ),
        migrations.CreateModel(
            name='AlertNotification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('channel', models.CharField(choices=[('zabbix', 'Zabbix'), ('telegram', 'Telegram'), ('email', 'E-mail'), ('webhook', 'Webhook')], max_length=20)),
                ('status', models.CharField(choices=[('pending', 'Pendente'), ('sent', 'Enviado'), ('failed', 'Falhou')], default='pending', max_length=20)),
                ('attempts', models.PositiveSmallIntegerField(default=0)),
                ('last_attempt_at', models.DateTimeField(blank=True, null=True)),
                ('sent_at', models.DateTimeField(blank=True, null=True)),
                ('response_message', models.TextField(blank=True)),
                ('alert', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to='alerts.alertevent')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='alertevent',
            index=models.Index(fields=['state', 'severity', '-opened_at'], name='alerts_aler_state_2aaef1_idx'),
        ),
        migrations.AddIndex(
            model_name='alertevent',
            index=models.Index(fields=['scope', 'state'], name='alerts_aler_scope_77c9ce_idx'),
        ),
        migrations.AddIndex(
            model_name='alertevent',
            index=models.Index(fields=['cto', 'state'], name='alerts_aler_cto_id_f6fa78_idx'),
        ),
        migrations.AddIndex(
            model_name='alertevent',
            index=models.Index(fields=['route', 'state'], name='alerts_aler_route_i_4f993b_idx'),
        ),
    ]
