# Generated by Django 5.2.16 on 2026-07-28 17:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('network_map', '0001_initial'),
        ('olt_integration', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='IXCConfiguration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(default='IXCSoft principal', max_length=120)),
                ('base_url', models.URLField()),
                ('api_token_encrypted', models.TextField(blank=True)),
                ('verify_ssl', models.BooleanField(default=True)),
                ('sync_interval_minutes', models.PositiveSmallIntegerField(default=5)),
                ('enabled', models.BooleanField(default=True)),
                ('last_sync_at', models.DateTimeField(blank=True, null=True)),
                ('last_sync_status', models.CharField(blank=True, max_length=30)),
                ('last_sync_message', models.TextField(blank=True)),
            ],
            options={
                'verbose_name': 'Configuração IXCSoft',
                'verbose_name_plural': 'Configurações IXCSoft',
            },
        ),
        migrations.CreateModel(
            name='IXCCustomer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('ixc_customer_id', models.CharField(max_length=80, unique=True)),
                ('name', models.CharField(db_index=True, max_length=180)),
                ('document', models.CharField(blank=True, max_length=30)),
                ('phone', models.CharField(blank=True, max_length=40)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('active', models.BooleanField(default=True)),
                ('raw_data', models.JSONField(blank=True, default=dict)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='IXCLogin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('ixc_login_id', models.CharField(max_length=80, unique=True)),
                ('username', models.CharField(db_index=True, max_length=180)),
                ('status', models.CharField(choices=[('normal', 'Normal'), ('warning', 'Atenção'), ('degraded', 'Degradado'), ('offline', 'Offline'), ('recovering', 'Recuperando'), ('no_data', 'Sem dados')], default='no_data', max_length=20)),
                ('online', models.BooleanField(default=False)),
                ('last_online_at', models.DateTimeField(blank=True, null=True)),
                ('last_offline_at', models.DateTimeField(blank=True, null=True)),
                ('last_synced_at', models.DateTimeField(blank=True, null=True)),
                ('raw_data', models.JSONField(blank=True, default=dict)),
                ('cto', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ixc_logins', to='network_map.cto')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='logins', to='ixc_integration.ixccustomer')),
                ('onu', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ixc_login', to='olt_integration.onu')),
            ],
            options={
                'ordering': ['username'],
            },
        ),
        migrations.CreateModel(
            name='IXCFiberAssignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('ixc_id', models.CharField(db_index=True, max_length=80, unique=True)),
                ('ixc_login_id', models.CharField(blank=True, db_index=True, max_length=80)),
                ('ixc_project_id', models.CharField(blank=True, db_index=True, max_length=80)),
                ('ixc_cto_id', models.CharField(blank=True, db_index=True, max_length=80)),
                ('ixc_transmitter_id', models.CharField(blank=True, max_length=80)),
                ('ixc_contract_id', models.CharField(blank=True, max_length=80)),
                ('ixc_hardware_id', models.CharField(blank=True, max_length=80)),
                ('name', models.CharField(blank=True, max_length=180)),
                ('mac_address', models.CharField(blank=True, db_index=True, max_length=32)),
                ('pon_id', models.CharField(blank=True, max_length=80)),
                ('slot_number', models.CharField(blank=True, max_length=30)),
                ('pon_number', models.CharField(blank=True, max_length=30)),
                ('onu_number', models.CharField(blank=True, max_length=30)),
                ('onu_type', models.CharField(blank=True, max_length=120)),
                ('vlan', models.CharField(blank=True, max_length=30)),
                ('vlan_pppoe', models.CharField(blank=True, max_length=30)),
                ('vlan_dhcp', models.CharField(blank=True, max_length=30)),
                ('gemport', models.CharField(blank=True, max_length=30)),
                ('service_port', models.CharField(blank=True, max_length=30)),
                ('cto_port', models.CharField(blank=True, max_length=30)),
                ('rx_power', models.DecimalField(blank=True, decimal_places=3, max_digits=8, null=True)),
                ('tx_power', models.DecimalField(blank=True, decimal_places=3, max_digits=8, null=True)),
                ('temperature', models.DecimalField(blank=True, decimal_places=3, max_digits=8, null=True)),
                ('voltage', models.DecimalField(blank=True, decimal_places=3, max_digits=8, null=True)),
                ('distance_meters', models.PositiveIntegerField(blank=True, null=True)),
                ('last_signal_at', models.DateTimeField(blank=True, null=True)),
                ('last_down_cause', models.CharField(blank=True, max_length=255)),
                ('management_ip', models.GenericIPAddressField(blank=True, null=True)),
                ('latitude', models.DecimalField(blank=True, decimal_places=7, max_digits=10, null=True)),
                ('longitude', models.DecimalField(blank=True, decimal_places=7, max_digits=10, null=True)),
                ('city', models.CharField(blank=True, max_length=120)),
                ('neighborhood', models.CharField(blank=True, max_length=120)),
                ('address', models.CharField(blank=True, max_length=255)),
                ('number', models.CharField(blank=True, max_length=30)),
                ('complement', models.CharField(blank=True, max_length=120)),
                ('postal_code', models.CharField(blank=True, max_length=20)),
                ('reference', models.CharField(blank=True, max_length=255)),
                ('raw_data', models.JSONField(blank=True, default=dict)),
                ('last_synced_at', models.DateTimeField(blank=True, null=True)),
                ('cto', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ixc_fiber_assignments', to='network_map.cto')),
                ('onu', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ixc_fiber_assignments', to='olt_integration.onu')),
                ('login', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='fiber_assignments', to='ixc_integration.ixclogin')),
            ],
            options={
                'ordering': ['name', 'ixc_id'],
            },
        ),
        migrations.CreateModel(
            name='IXCSyncExecution',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('status', models.CharField(choices=[('running', 'Executando'), ('success', 'Sucesso'), ('failed', 'Falhou'), ('partial', 'Parcial')], default='running', max_length=20)),
                ('started_at', models.DateTimeField()),
                ('finished_at', models.DateTimeField(blank=True, null=True)),
                ('records_received', models.PositiveIntegerField(default=0)),
                ('records_created', models.PositiveIntegerField(default=0)),
                ('records_updated', models.PositiveIntegerField(default=0)),
                ('records_failed', models.PositiveIntegerField(default=0)),
                ('error_message', models.TextField(blank=True)),
                ('configuration', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='executions', to='ixc_integration.ixcconfiguration')),
            ],
            options={
                'ordering': ['-started_at'],
            },
        ),
        migrations.AddIndex(
            model_name='ixclogin',
            index=models.Index(fields=['cto', 'online'], name='ixc_integra_cto_id_10de7a_idx'),
        ),
        migrations.AddIndex(
            model_name='ixclogin',
            index=models.Index(fields=['status', 'online'], name='ixc_integra_status_ba28a0_idx'),
        ),
        migrations.AddIndex(
            model_name='ixcfiberassignment',
            index=models.Index(fields=['ixc_cto_id', 'ixc_login_id'], name='ixc_integra_ixc_cto_96345c_idx'),
        ),
        migrations.AddIndex(
            model_name='ixcfiberassignment',
            index=models.Index(fields=['mac_address', 'onu_number'], name='ixc_integra_mac_add_27b69e_idx'),
        ),
        migrations.AddIndex(
            model_name='ixcfiberassignment',
            index=models.Index(fields=['ixc_project_id'], name='ixc_integra_ixc_pro_fe21e8_idx'),
        ),
        migrations.AddIndex(
            model_name='ixcsyncexecution',
            index=models.Index(fields=['configuration', '-started_at'], name='ixc_integra_configu_068d94_idx'),
        ),
        migrations.AddIndex(
            model_name='ixcsyncexecution',
            index=models.Index(fields=['status', '-started_at'], name='ixc_integra_status_990275_idx'),
        ),
    ]
