# Generated by Django 5.2.16 on 2026-07-28 22:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
        ('ixc_integration', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='ixcconfiguration',
            name='company',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ixc_configurations', to='core.company'),
        ),
    ]
