# Generated by Django 5.2.16 on 2026-07-28 17:15

import django.contrib.gis.db.models.fields
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='NetworkElement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(db_index=True, max_length=180)),
                ('description', models.TextField(blank=True)),
                ('code', models.CharField(blank=True, db_index=True, max_length=100)),
                ('element_type', models.CharField(choices=[('olt', 'OLT'), ('dio', 'DIO'), ('splice_box', 'Caixa de emenda'), ('cto', 'CTO'), ('pole', 'Poste'), ('cabinet', 'Armário'), ('other', 'Outro')], max_length=30)),
                ('point', django.contrib.gis.db.models.fields.PointField(blank=True, null=True, srid=4326)),
                ('status', models.CharField(choices=[('normal', 'Normal'), ('warning', 'Atenção'), ('degraded', 'Degradado'), ('offline', 'Offline'), ('recovering', 'Recuperando'), ('no_data', 'Sem dados')], default='no_data', max_length=20)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('enabled', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['element_type', 'name'],
            },
        ),
        migrations.CreateModel(
            name='FiberCable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(db_index=True, max_length=180)),
                ('description', models.TextField(blank=True)),
                ('code', models.CharField(blank=True, db_index=True, max_length=100)),
                ('cable_type', models.CharField(choices=[('feeder', 'Alimentador'), ('distribution', 'Distribuição'), ('drop', 'Drop'), ('backbone', 'Backbone')], max_length=30)),
                ('geometry', django.contrib.gis.db.models.fields.MultiLineStringField(srid=4326)),
                ('fiber_count', models.PositiveSmallIntegerField(default=12)),
                ('used_fibers', models.PositiveSmallIntegerField(default=0)),
                ('status', models.CharField(choices=[('normal', 'Normal'), ('warning', 'Atenção'), ('degraded', 'Degradado'), ('offline', 'Offline'), ('recovering', 'Recuperando'), ('no_data', 'Sem dados')], default='no_data', max_length=20)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='NetworkDependency',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('fiber_identifier', models.CharField(blank=True, max_length=80)),
                ('notes', models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='NetworkRoute',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(db_index=True, max_length=180)),
                ('description', models.TextField(blank=True)),
                ('code', models.CharField(max_length=80, unique=True)),
                ('geometry', django.contrib.gis.db.models.fields.MultiLineStringField(blank=True, null=True, srid=4326)),
                ('status', models.CharField(choices=[('normal', 'Normal'), ('warning', 'Atenção'), ('degraded', 'Degradado'), ('offline', 'Offline'), ('recovering', 'Recuperando'), ('no_data', 'Sem dados')], default='no_data', max_length=20)),
                ('offline_cto_threshold', models.PositiveSmallIntegerField(default=2)),
                ('offline_cto_percentage', models.DecimalField(decimal_places=2, default=50, max_digits=5)),
                ('enabled', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='CTO',
            fields=[
                ('networkelement_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='network_map.networkelement')),
                ('ixc_box_id', models.CharField(blank=True, max_length=80, null=True, unique=True)),
                ('capacity', models.PositiveSmallIntegerField(default=16)),
                ('splitter_ratio', models.CharField(blank=True, max_length=30)),
                ('offline_onu_threshold', models.PositiveSmallIntegerField(default=3)),
                ('offline_onu_percentage', models.DecimalField(decimal_places=2, default=60, max_digits=5)),
                ('los_onu_threshold', models.PositiveSmallIntegerField(default=2)),
                ('los_onu_percentage', models.DecimalField(decimal_places=2, default=50, max_digits=5)),
                ('last_evaluated_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'CTO',
                'verbose_name_plural': 'CTOs',
            },
            bases=('network_map.networkelement',),
        ),
        migrations.AddIndex(
            model_name='networkelement',
            index=models.Index(fields=['element_type', 'status'], name='network_map_element_31aa30_idx'),
        ),
        migrations.AddIndex(
            model_name='networkelement',
            index=models.Index(fields=['code'], name='network_map_code_0c6c00_idx'),
        ),
        migrations.AddField(
            model_name='fibercable',
            name='destination',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='incoming_cables', to='network_map.networkelement'),
        ),
        migrations.AddField(
            model_name='fibercable',
            name='origin',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='outgoing_cables', to='network_map.networkelement'),
        ),
        migrations.AddField(
            model_name='networkdependency',
            name='downstream',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='upstream_dependencies', to='network_map.networkelement'),
        ),
        migrations.AddField(
            model_name='networkdependency',
            name='upstream',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='downstream_dependencies', to='network_map.networkelement'),
        ),
        migrations.AddIndex(
            model_name='networkroute',
            index=models.Index(fields=['status', 'enabled'], name='network_map_status_7e08e9_idx'),
        ),
        migrations.AddField(
            model_name='fibercable',
            name='route',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cables', to='network_map.networkroute'),
        ),
        migrations.AddField(
            model_name='cto',
            name='route',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ctos', to='network_map.networkroute'),
        ),
        migrations.AddConstraint(
            model_name='networkdependency',
            constraint=models.UniqueConstraint(fields=('upstream', 'downstream'), name='unique_network_dependency'),
        ),
    ]
