# Generated by Django 5.2.16 on 2026-07-28 22:02

import django.contrib.gis.db.models.fields
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
        ('network_map', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='FiberColor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=30, unique=True, verbose_name='Código')),
                ('name', models.CharField(max_length=80, verbose_name='Nome')),
                ('hex_color', models.CharField(default='#000000', max_length=7, verbose_name='Cor hexadecimal')),
                ('text_color', models.CharField(default='#FFFFFF', max_length=7, verbose_name='Cor do texto')),
                ('order', models.PositiveSmallIntegerField(default=1, verbose_name='Ordem')),
            ],
            options={
                'verbose_name': 'Cor de fibra',
                'verbose_name_plural': 'Cores de fibra',
                'ordering': ['order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='CableModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(db_index=True, max_length=180)),
                ('description', models.TextField(blank=True)),
                ('manufacturer', models.CharField(blank=True, max_length=120, verbose_name='Fabricante')),
                ('model', models.CharField(max_length=120, verbose_name='Modelo')),
                ('construction', models.CharField(choices=[('loose_tube', 'Loose tube'), ('tight_buffer', 'Tight buffer'), ('ribbon', 'Ribbon'), ('drop', 'Drop'), ('other', 'Outro')], default='loose_tube', max_length=30, verbose_name='Construção')),
                ('fiber_count', models.PositiveSmallIntegerField(verbose_name='Quantidade de fibras')),
                ('tube_count', models.PositiveSmallIntegerField(default=1, verbose_name='Quantidade de tubos')),
                ('fibers_per_tube', models.PositiveSmallIntegerField(default=12, verbose_name='Fibras por tubo')),
                ('outer_diameter_mm', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True, verbose_name='Diâmetro externo em mm')),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('company', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='core.company')),
            ],
            options={
                'verbose_name': 'Modelo de cabo',
                'verbose_name_plural': 'Modelos de cabo',
                'ordering': ['manufacturer', 'model'],
            },
        ),
        migrations.AddField(
            model_name='fibercable',
            name='cable_model',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='installed_cables', to='network_map.cablemodel', verbose_name='Modelo do cabo'),
        ),
        migrations.CreateModel(
            name='FiberColorStandard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(db_index=True, max_length=180)),
                ('code', models.CharField(db_index=True, max_length=80, verbose_name='Código')),
                ('description', models.TextField(blank=True, verbose_name='Descrição')),
                ('company', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='core.company')),
            ],
            options={
                'verbose_name': 'Padrão de cores',
                'verbose_name_plural': 'Padrões de cores',
                'ordering': ['name'],
            },
        ),
        migrations.AddField(
            model_name='cablemodel',
            name='color_standard',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='cable_models', to='network_map.fibercolorstandard', verbose_name='Padrão de cores'),
        ),
        migrations.CreateModel(
            name='FiberColorStandardItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position', models.PositiveSmallIntegerField(verbose_name='Posição')),
                ('color', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='standard_items', to='network_map.fibercolor', verbose_name='Cor')),
                ('standard', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='network_map.fibercolorstandard', verbose_name='Padrão')),
            ],
            options={
                'verbose_name': 'Item do padrão de cores',
                'verbose_name_plural': 'Itens do padrão de cores',
                'ordering': ['standard', 'position'],
            },
        ),
        migrations.CreateModel(
            name='FiberTube',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('number', models.PositiveSmallIntegerField(verbose_name='Número')),
                ('identification', models.CharField(blank=True, max_length=80, verbose_name='Identificação')),
                ('cable', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tubes', to='network_map.fibercable', verbose_name='Cabo')),
                ('color', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='fiber_tubes', to='network_map.fibercolor', verbose_name='Cor')),
            ],
            options={
                'verbose_name': 'Tubo de fibra',
                'verbose_name_plural': 'Tubos de fibra',
                'ordering': ['cable', 'number'],
            },
        ),
        migrations.CreateModel(
            name='FiberStrand',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('number', models.PositiveSmallIntegerField(verbose_name='Número global')),
                ('position_in_tube', models.PositiveSmallIntegerField(verbose_name='Posição no tubo')),
                ('status', models.CharField(choices=[('free', 'Livre'), ('used', 'Em uso'), ('reserved', 'Reservada'), ('damaged', 'Danificada'), ('dark', 'Apagada')], default='free', max_length=20, verbose_name='Estado')),
                ('usage', models.CharField(blank=True, max_length=180, verbose_name='Uso')),
                ('notes', models.TextField(blank=True, verbose_name='Observações')),
                ('cable', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fibers', to='network_map.fibercable', verbose_name='Cabo')),
                ('color', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='fiber_strands', to='network_map.fibercolor', verbose_name='Cor')),
                ('destination_element', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='destination_fibers', to='network_map.networkelement', verbose_name='Destino')),
                ('origin_element', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='origin_fibers', to='network_map.networkelement', verbose_name='Origem')),
                ('tube', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='fibers', to='network_map.fibertube', verbose_name='Tubo')),
            ],
            options={
                'verbose_name': 'Fibra',
                'verbose_name_plural': 'Fibras',
                'ordering': ['cable', 'number'],
            },
        ),
        migrations.CreateModel(
            name='POP',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(db_index=True, max_length=180)),
                ('description', models.TextField(blank=True)),
                ('code', models.CharField(db_index=True, max_length=100, verbose_name='Código')),
                ('point', django.contrib.gis.db.models.fields.PointField(blank=True, null=True, srid=4326, verbose_name='Localização')),
                ('address', models.CharField(blank=True, max_length=255, verbose_name='Endereço')),
                ('city', models.CharField(blank=True, max_length=120, verbose_name='Cidade')),
                ('enabled', models.BooleanField(default=True, verbose_name='Ativo')),
                ('company', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='core.company')),
            ],
            options={
                'verbose_name': 'POP',
                'verbose_name_plural': 'POPs',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Rack',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(db_index=True, max_length=180)),
                ('description', models.TextField(blank=True)),
                ('code', models.CharField(db_index=True, max_length=100, verbose_name='Código')),
                ('height_units', models.PositiveSmallIntegerField(default=44, verbose_name='Altura em U')),
                ('manufacturer', models.CharField(blank=True, max_length=120, verbose_name='Fabricante')),
                ('model', models.CharField(blank=True, max_length=120, verbose_name='Modelo')),
                ('enabled', models.BooleanField(default=True, verbose_name='Ativo')),
                ('company', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='core.company')),
                ('pop', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='racks', to='network_map.pop', verbose_name='POP')),
            ],
            options={
                'verbose_name': 'Rack',
                'verbose_name_plural': 'Racks',
                'ordering': ['pop', 'code'],
            },
        ),
        migrations.CreateModel(
            name='RackEquipment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=180, verbose_name='Equipamento')),
                ('equipment_type', models.CharField(max_length=80, verbose_name='Tipo')),
                ('manufacturer', models.CharField(blank=True, max_length=120, verbose_name='Fabricante')),
                ('model', models.CharField(blank=True, max_length=120, verbose_name='Modelo')),
                ('serial_number', models.CharField(blank=True, max_length=120, verbose_name='Número de série')),
                ('start_unit', models.PositiveSmallIntegerField(verbose_name='U inicial')),
                ('unit_height', models.PositiveSmallIntegerField(default=1, verbose_name='Altura em U')),
                ('face', models.CharField(choices=[('front', 'Frontal'), ('rear', 'Traseira'), ('both', 'Frontal e traseira')], default='front', max_length=10, verbose_name='Face')),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('rack', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='equipments', to='network_map.rack', verbose_name='Rack')),
            ],
            options={
                'verbose_name': 'Equipamento de rack',
                'verbose_name_plural': 'Equipamentos de rack',
                'ordering': ['rack', '-start_unit'],
            },
        ),
        migrations.AddConstraint(
            model_name='fibercolorstandard',
            constraint=models.UniqueConstraint(fields=('company', 'code'), name='unique_color_standard_per_company'),
        ),
        migrations.AddConstraint(
            model_name='cablemodel',
            constraint=models.UniqueConstraint(fields=('company', 'manufacturer', 'model'), name='unique_cable_model_per_company'),
        ),
        migrations.AddConstraint(
            model_name='fibercolorstandarditem',
            constraint=models.UniqueConstraint(fields=('standard', 'position'), name='unique_color_position_per_standard'),
        ),
        migrations.AddConstraint(
            model_name='fibertube',
            constraint=models.UniqueConstraint(fields=('cable', 'number'), name='unique_tube_number_per_cable'),
        ),
        migrations.AddConstraint(
            model_name='fiberstrand',
            constraint=models.UniqueConstraint(fields=('cable', 'number'), name='unique_fiber_number_per_cable'),
        ),
        migrations.AddConstraint(
            model_name='fiberstrand',
            constraint=models.UniqueConstraint(fields=('tube', 'position_in_tube'), name='unique_fiber_position_per_tube'),
        ),
        migrations.AddConstraint(
            model_name='pop',
            constraint=models.UniqueConstraint(fields=('company', 'code'), name='unique_pop_code_per_company'),
        ),
        migrations.AddConstraint(
            model_name='rack',
            constraint=models.UniqueConstraint(fields=('pop', 'code'), name='unique_rack_code_per_pop'),
        ),
        migrations.AddConstraint(
            model_name='rackequipment',
            constraint=models.UniqueConstraint(fields=('rack', 'start_unit', 'face'), name='unique_rack_unit_face'),
        ),
    ]
