# Generated by Django 5.2.16 on 2026-07-28 23:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('network_map', '0003_sync_company_fields_state'),
    ]

    operations = [
        migrations.CreateModel(
            name='SpliceTray',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('number', models.PositiveSmallIntegerField(verbose_name='Bandeja')),
                ('name', models.CharField(blank=True, max_length=100)),
                ('capacity', models.PositiveSmallIntegerField(default=12, verbose_name='Capacidade')),
                ('splice_box', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='splice_trays', to='network_map.networkelement', verbose_name='Caixa')),
            ],
            options={
                'verbose_name': 'Bandeja de emenda',
                'verbose_name_plural': 'Bandejas de emenda',
                'ordering': ['splice_box', 'number'],
                'unique_together': {('splice_box', 'number')},
            },
        ),
        migrations.CreateModel(
            name='FiberSplice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('loss_db', models.DecimalField(decimal_places=2, default=0.05, max_digits=4, verbose_name='Perda (dB)')),
                ('notes', models.TextField(blank=True)),
                ('input_fiber', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='splice_output', to='network_map.fiberstrand', verbose_name='Fibra de entrada')),
                ('output_fiber', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='splice_input', to='network_map.fiberstrand', verbose_name='Fibra de saída')),
                ('splice_box', models.ForeignKey(limit_choices_to={'element_type': 'dio'}, on_delete=django.db.models.deletion.CASCADE, related_name='fiber_splices', to='network_map.networkelement', verbose_name='Caixa de emenda')),
                ('tray', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='splices', to='network_map.splicetray', verbose_name='Bandeja')),
            ],
            options={
                'verbose_name': 'Emenda óptica',
                'verbose_name_plural': 'Emendas ópticas',
                'ordering': ['splice_box', 'id'],
            },
        ),
    ]
