# Generated by Django 5.2.16 on 2026-07-29 00:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('network_map', '0004_splicetray_fibersplice'),
    ]

    operations = [
        migrations.AddField(
            model_name='fibersplice',
            name='position',
            field=models.PositiveSmallIntegerField(default=1, verbose_name='Posição da fusão'),
        ),
    ]
