[[inputs.snmp]]
  agents = ["{{IP_DO_EQUIPAMENTO}}:{{PORTA}}"]
  version = 2
  community = "{{COMMUNITY_DO_EQUIPAMENTO}}"
  interval = "{{INTERVALO}}s"

  [inputs.snmp.tags]
    equipamento_id = "{{ID_NO_BANCO_DE_DADOS}}"

  [[inputs.snmp.field]]
    name = "hostname"
    oid = ".1.3.6.1.2.1.1.5.0"
    is_tag = true

  [[inputs.snmp.table]]
    name = "porta_status"
    inherit_tags = ["hostname"]
    oid = ".1.3.6.1.2.1.31.1.1"

    [[inputs.snmp.table.field]]
      name = "porta_nome"
      oid = ".1.3.6.1.2.1.31.1.1.1.1"
      is_tag = true

    [[inputs.snmp.table.field]]
      name = "status_operacional"
      oid = ".1.3.6.1.2.1.2.2.1.8"
