# Generated by Django 5.2.16 on 2026-07-28 20:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AccessPoint',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('source', models.CharField(db_index=True, default='ixc', max_length=50, verbose_name='Origem')),
                ('external_id', models.CharField(db_index=True, max_length=100, verbose_name='ID externo')),
                ('ixc_customer_id', models.CharField(blank=True, db_index=True, max_length=80, verbose_name='ID Cliente IXC')),
                ('ixc_contract_id', models.CharField(blank=True, db_index=True, max_length=80, verbose_name='ID Contrato IXC')),
                ('username', models.CharField(blank=True, db_index=True, max_length=180, verbose_name='Login PPPoE')),
                ('customer_name', models.CharField(blank=True, max_length=180, verbose_name='Cliente')),
                ('status', models.CharField(choices=[('online', 'Online'), ('offline', 'Offline'), ('unknown', 'Desconhecido')], db_index=True, default='unknown', max_length=20)),
                ('online', models.BooleanField(db_index=True, default=False)),
                ('latitude', models.DecimalField(blank=True, decimal_places=7, max_digits=10, null=True)),
                ('longitude', models.DecimalField(blank=True, decimal_places=7, max_digits=10, null=True)),
                ('onu_mac', models.CharField(blank=True, db_index=True, max_length=80, verbose_name='MAC ONU')),
                ('cto_ixc_id', models.CharField(blank=True, db_index=True, max_length=80, verbose_name='ID CTO IXC')),
                ('ftth_port', models.CharField(blank=True, max_length=30, verbose_name='Porta FTTH')),
                ('concentrator_id', models.CharField(blank=True, max_length=80, verbose_name='ID Concentrador')),
                ('concentrator', models.CharField(blank=True, max_length=120, verbose_name='Concentrador')),
                ('interface_transmission', models.CharField(blank=True, max_length=120, verbose_name='Interface transmissão')),
                ('connection_type', models.CharField(blank=True, max_length=80, verbose_name='Tipo conexão')),
                ('last_connection_start', models.DateTimeField(blank=True, null=True)),
                ('last_connection_end', models.DateTimeField(blank=True, null=True)),
                ('disconnect_reason', models.CharField(blank=True, max_length=255)),
                ('last_seen_at', models.DateTimeField(blank=True, null=True)),
                ('raw_data', models.JSONField(blank=True, default=dict)),
                ('company', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='core.company')),
            ],
            options={
                'verbose_name': 'Ponto de acesso',
                'verbose_name_plural': 'Pontos de acesso',
                'ordering': ['customer_name'],
                'indexes': [models.Index(fields=['company', 'online'], name='access_acce_company_304e94_idx'), models.Index(fields=['company', 'status'], name='access_acce_company_96505f_idx'), models.Index(fields=['onu_mac'], name='access_acce_onu_mac_fa8292_idx'), models.Index(fields=['cto_ixc_id'], name='access_acce_cto_ixc_482b57_idx')],
                'constraints': [models.UniqueConstraint(fields=('company', 'source', 'external_id'), name='unique_accesspoint_source_external')],
            },
        ),
    ]
