# Generated by Django 5.2.16 on 2026-07-28 17:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='OLT',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(db_index=True, max_length=180)),
                ('description', models.TextField(blank=True)),
                ('hostname', models.CharField(blank=True, max_length=120)),
                ('management_ip', models.GenericIPAddressField(unique=True)),
                ('vendor', models.CharField(choices=[('fiberhome', 'FiberHome'), ('huawei', 'Huawei'), ('zte', 'ZTE'), ('other', 'Outro')], default='fiberhome', max_length=30)),
                ('model', models.CharField(blank=True, max_length=120)),
                ('serial_number', models.CharField(blank=True, max_length=120)),
                ('snmp_version', models.CharField(choices=[('2c', 'SNMP v2c'), ('3', 'SNMP v3')], default='2c', max_length=10)),
                ('snmp_port', models.PositiveIntegerField(default=161)),
                ('snmp_community_encrypted', models.TextField(blank=True)),
                ('snmp_username', models.CharField(blank=True, max_length=120)),
                ('snmp_auth_key_encrypted', models.TextField(blank=True)),
                ('snmp_priv_key_encrypted', models.TextField(blank=True)),
                ('enabled', models.BooleanField(default=True)),
                ('polling_interval_seconds', models.PositiveIntegerField(default=120)),
                ('status', models.CharField(choices=[('normal', 'Normal'), ('warning', 'Atenção'), ('degraded', 'Degradado'), ('offline', 'Offline'), ('recovering', 'Recuperando'), ('no_data', 'Sem dados')], default='no_data', max_length=20)),
                ('last_seen_at', models.DateTimeField(blank=True, null=True)),
                ('last_poll_at', models.DateTimeField(blank=True, null=True)),
                ('last_poll_message', models.TextField(blank=True)),
            ],
            options={
                'ordering': ['name'],
                'indexes': [models.Index(fields=['enabled', 'status'], name='olt_integra_enabled_852b63_idx'), models.Index(fields=['vendor', 'model'], name='olt_integra_vendor_bbe595_idx')],
            },
        ),
        migrations.CreateModel(
            name='PONPort',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('frame', models.PositiveSmallIntegerField(default=0)),
                ('slot', models.PositiveSmallIntegerField()),
                ('port', models.PositiveSmallIntegerField()),
                ('interface_name', models.CharField(blank=True, max_length=120)),
                ('description', models.CharField(blank=True, max_length=255)),
                ('capacity', models.PositiveSmallIntegerField(default=128)),
                ('status', models.CharField(choices=[('normal', 'Normal'), ('warning', 'Atenção'), ('degraded', 'Degradado'), ('offline', 'Offline'), ('recovering', 'Recuperando'), ('no_data', 'Sem dados')], default='no_data', max_length=20)),
                ('last_seen_at', models.DateTimeField(blank=True, null=True)),
                ('olt', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pon_ports', to='olt_integration.olt')),
            ],
            options={
                'ordering': ['olt', 'frame', 'slot', 'port'],
            },
        ),
        migrations.CreateModel(
            name='ONU',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('onu_id', models.PositiveSmallIntegerField()),
                ('serial_number', models.CharField(blank=True, db_index=True, max_length=120)),
                ('mac_address', models.CharField(blank=True, db_index=True, max_length=32)),
                ('model', models.CharField(blank=True, max_length=120)),
                ('firmware_version', models.CharField(blank=True, max_length=120)),
                ('registration_status', models.CharField(choices=[('registered', 'Registrada'), ('unregistered', 'Não registrada'), ('unknown', 'Desconhecida')], default='unknown', max_length=20)),
                ('operational_status', models.CharField(choices=[('normal', 'Normal'), ('warning', 'Atenção'), ('degraded', 'Degradado'), ('offline', 'Offline'), ('recovering', 'Recuperando'), ('no_data', 'Sem dados')], default='no_data', max_length=20)),
                ('los', models.BooleanField(default=False)),
                ('rx_power', models.DecimalField(blank=True, decimal_places=3, max_digits=7, null=True)),
                ('tx_power', models.DecimalField(blank=True, decimal_places=3, max_digits=7, null=True)),
                ('temperature', models.DecimalField(blank=True, decimal_places=2, max_digits=7, null=True)),
                ('voltage', models.DecimalField(blank=True, decimal_places=3, max_digits=8, null=True)),
                ('distance_meters', models.PositiveIntegerField(blank=True, null=True)),
                ('last_seen_at', models.DateTimeField(blank=True, null=True)),
                ('last_collected_at', models.DateTimeField(blank=True, null=True)),
                ('pon_port', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='onus', to='olt_integration.ponport')),
            ],
            options={
                'ordering': ['pon_port', 'onu_id'],
            },
        ),
        migrations.CreateModel(
            name='ONUSignalHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('collected_at', models.DateTimeField(db_index=True)),
                ('operational_status', models.CharField(choices=[('normal', 'Normal'), ('warning', 'Atenção'), ('degraded', 'Degradado'), ('offline', 'Offline'), ('recovering', 'Recuperando'), ('no_data', 'Sem dados')], max_length=20)),
                ('los', models.BooleanField(default=False)),
                ('rx_power', models.DecimalField(blank=True, decimal_places=3, max_digits=7, null=True)),
                ('tx_power', models.DecimalField(blank=True, decimal_places=3, max_digits=7, null=True)),
                ('temperature', models.DecimalField(blank=True, decimal_places=2, max_digits=7, null=True)),
                ('voltage', models.DecimalField(blank=True, decimal_places=3, max_digits=8, null=True)),
                ('source', models.CharField(default='snmp', max_length=30)),
                ('onu', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='signal_history', to='olt_integration.onu')),
            ],
            options={
                'ordering': ['-collected_at'],
                'indexes': [models.Index(fields=['onu', '-collected_at'], name='olt_integra_onu_id_74c0ab_idx'), models.Index(fields=['operational_status', '-collected_at'], name='olt_integra_operati_63552a_idx')],
            },
        ),
        migrations.AddIndex(
            model_name='ponport',
            index=models.Index(fields=['olt', 'status'], name='olt_integra_olt_id_9a0baa_idx'),
        ),
        migrations.AddConstraint(
            model_name='ponport',
            constraint=models.UniqueConstraint(fields=('olt', 'frame', 'slot', 'port'), name='unique_olt_frame_slot_port'),
        ),
        migrations.AddIndex(
            model_name='onu',
            index=models.Index(fields=['operational_status', 'los'], name='olt_integra_operati_398c90_idx'),
        ),
        migrations.AddIndex(
            model_name='onu',
            index=models.Index(fields=['pon_port', 'operational_status'], name='olt_integra_pon_por_6ff62c_idx'),
        ),
        migrations.AddIndex(
            model_name='onu',
            index=models.Index(fields=['last_collected_at'], name='olt_integra_last_co_4c0b6b_idx'),
        ),
        migrations.AddConstraint(
            model_name='onu',
            constraint=models.UniqueConstraint(fields=('pon_port', 'onu_id'), name='unique_onu_per_pon'),
        ),
    ]
